CREATE TABLE USUARIO (ID_USUARIO INTEGER AUTO_INCREMENT PRIMARY KEY,
LOGIN VARCHAR(20),
PASSWORD VARCHAR(20)); 
CREATE TABLE USUARIO(ID_USUARIO INTEGER AUTO_INCREMENT PRIMARY KEY,
ID_DIRECCION INTEGER,
LOGIN VARCHAR(20),
PASSWORD VARCHAR(20),
EMAIL VARCHAR(40),
FOREIGN KEY(ID_DIRECCION) REFERENCES DIRECCION(ID_DIRECCION));

CREATE TABLE DIRECCION(ID_DIRECCION INTEGER AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100),
NUMERO INTEGER,
COLONIA VARCHAR(20),
MUNICIPIO VARCHAR(60));

SELECT * FROM USUARIO;